const { speedtest } = require('./commands/speedtest')

testcommand = require('./commands/testcommand')
ping = require('./commands/ping')
avatar = require('./commands/avatar')
info = require('./commands/info')
serverinfo = require('./commands/serverinfo')
help = require('./commands/help')
meme = require('./commands/meme')
pcusage = require('./commands/usage')
getmcskin = require('./commands/getskin')
version = require("./package.json").version
todo = require("./commands/todo")
suggestion = require("./commands/suggestion")
speedtest_test = require("./commands/speedtest")